GENOME: "mm10"
REFFA: "/data/CCBR_Pipeliner/db/PipeDB/Indices/mm10_basic/ref.fa"
GTFFILE: "/data/CCBR_Pipeliner/db/PipeDB/Indices/mm10_basic/genes.gtf"
OUTDIR: "/scratch/Testing/PIM/output/"
SCRIPTSDIR: "/spin1/scratch/CCBRPipeliner/PIM_TESTING/PIM/src/Scripts"
PIM_HOME: "/spin1/scratch/CCBRPipeliner/PIM_TESTING/PIM"
GENOME: "mm10"
READLENGTHS:
  - 50
  - 75
  - 100
  - 125
  - 150
